import { IconDefinition } from '@fortawesome/angular-fontawesome';
import {
  faArrowRightFromBracket,
  faBars, faBell,
  faBook, faChartSimple,
  faCircleCheck, faCircleExclamation,
  faClock,
  faCogs, faComments, faDollarSign,
  faEnvelope, faEye,
  faGavel, faHeart,
  faKey,
  faMapMarkerAlt, faMessage,
  faMoneyBill1, faMoneyBillWave,
  faPencil,
  faPlus,
  faSearch, faSignInAlt, faTrash,
  faUser,
  faHourglass, faPen, faTrophy, faNewspaper, faLanguage
} from '@fortawesome/free-solid-svg-icons';
import {
  faFacebook,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

export const fontAwesomeIcons: IconDefinition[] = [
  faUser,
  faBook,
  faYoutube,
  faFacebook,
  faTwitter,
  faSearch,
  faBars,
  faEnvelope,
  faKey,
  faUser,
  faMoneyBill1,
  faMapMarkerAlt,
  faClock,
  faCircleCheck,
  faPlus,
  faPencil,
  faCogs,
  faGavel,
  faArrowRightFromBracket,
  faMessage,
  faSignInAlt,
  faEye,
  faComments,
  faHeart,
  faChartSimple,
  faDollarSign,
  faBell,
  faTrash,
  faPlus,
  faCircleExclamation,
  faHourglass,
  faPen,
  faTrophy,
  faNewspaper,
  faLanguage
];
